# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12200d71e4b7029ea56a429e24260c6c0e85a3069b0d4ba85eace21a0fd75910aa64";
    path = fetchzip {
      url = "https://github.com/ziglibs/diffz/archive/e10bf15962e45affb3fcd7d9a950977a69c901b3.tar.gz";
      hash = "sha256-yVFPVn4jGfcoE2V4xdTqdThYPutshL6U4feDzetWgFw=";
    };
  }
  {
    name = "12209925016f4b5486a713828ead3bcc900fa4f039c93de1894aa7d5253f7633b92c";
    path = fetchzip {
      url = "https://github.com/ziglibs/known-folders/archive/2aa7f2e9855d45b20072e15107fb379b9380adbe.tar.gz";
      hash = "sha256-YibEEVTkcaC5F9LzaPRdTvZjqv9CqNfI7dEla4E5PNs=";
    };
  }
]
