name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        A bug is when something works differently than it is expected to.
        ## Remember to search before filing a new report
        Please search for this bug in the issue tracker, and use a bug report title that
        would have made your bug report turn up in the search results for your search query.
  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      description: "The output of `zig version`"
      placeholder: "0.9.0-dev.1275+ac52e0056"
    validations:
      required: true
  - type: input
    id: zls-version
    attributes:
      label: Zig Language Server Version
      description: "Your zls release or commit"
      placeholder: "b21039d51261923c665d3bc58fadc4b4d5e221ea"
    validations:
      required: true
  - type: input
    id: editor
    attributes:
      label: Client / Code Editor / Extensions
      description: What client/code editor/extensions are you using, if any?
      placeholder: "nvim 0.9.4 with CoC and ziglang/zig.vim"
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce and Observed Behavior
      description: What exactly can someone else do, in order to observe the problem that you observed?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, include ZLS's log output [Guide](https://github.com/zigtools/zls/wiki/Guide:-How-to-view-ZLS-log-output). This will be automatically formatted into monospace, so no need for backticks.
      render: shell
    validations:
      required: false